### ISSUE TITLE
Lots of broken links on https://emojitwo.github.io/

### ISSUE THREAD

**Issue by afmenez** [EmojiTwo/emojitwo#160]
There are lots of broken links on the main page.
Ex.: https://emojitwo.github.io/EmojiTwo/emojitwo/issues/ -> https://github.com/EmojiTwo/emojitwo/issues/

I believe many of them are relative when then should be absolute.

**Comment by Crissov** [comment]
Thank you. I found two relative URLs and fixed them, also added explicit link markdown for bare URLs.

The homepage is currently maintained manually, i.e. it is not automatically synced with changes to the repository. Also see your issue #161.
