### ISSUE TITLE
Flag organization

### ISSUE THREAD

**Issue by bhargavgv** [EmojiTwo/emojitwo#164]
How are the flags in this repo organized? I'm having a hard time finding them.

**Comment by Crissov** [comment]
As in most emoji projects glyph files are named by their sequence of hexadecimal Unicode code points. National flags are combinations of 2 characters in the range U+1F1E6..1F1FF called [Regional Indicator Symbols](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol).

**Comment by bhargavgv** [comment]
I get it now.
