### ISSUE TITLE
Flag for United Nations

### ISSUE THREAD

**Issue by KAMiKAZOW** [EmojiTwo/emojitwo#64]
Emoji 4.0 sequence for the UN flag is missing

http://emojipedia.org/flag-for-united-nations/

**Comment by Crissov** [comment]
`UN` U+1F1FA+1F1F3 🇺🇳

![master branch](https://raw.githubusercontent.com/EmojiTwo/emojitwo/master/png/1f1fa-1f1f3.png) [![emoji4 branch](https://raw.githubusercontent.com/EmojiTwo/emojitwo/emoji4/png/1f1fa-1f1f3.png)](https://github.com/EmojiTwo/emojitwo/blob/emoji4/svg/1f1fa-1f1f3.svg)

**Comment by Crissov** [comment]
The `emoji4` branch now contains `1f1fa-1f1f3.svg`.
