### ISSUE TITLE
Add emojitwo to a cdn somewhere

### ISSUE THREAD

**Issue by mika76** [EmojiTwo/emojitwo#68]
this would be a huge help for css and emojitwo-awesome use...

**Comment by Crissov** [comment]
Does rawgit.com count?

If we can significantly improve Emojitwo over Emojione 2.2, we should probably make it as easy to use as possible, but for now, adding it to a CDN is not a priority, I think.

**Comment by NicoWeio** [comment]
raw.githubusercontent.com might work for you.
Example: [here](https://raw.githubusercontent.com/emojitwo/emojitwo/master/png/1f418-1f464.png)

**Comment by mika76** [comment]
Well yeah https://github.com/EmojiTwo/emojitwo/blob/master/css/emojitwo-awesome.css does use rawgit, but it's pointing to the old emojione project.

 The thing is. rawgit is not really promoted as a cdn so I thought it would be better to use a proper cdn...

Anyway you're welcome to close this issue if it's not something you're planning on doing.

**Comment by NicoWeio** [comment]
I don't see a single rawgit.com link in that file. 😅
Anyway, you can use services like [jsdelivr.com](https://jsdelivr.com), [statically.io](https://statically.io/) or [raw.githack.com](https://raw.githack.com/). No further steps required.

**Comment by mika76** [comment]
I must have been seeing things. Thanks for your help...
