### ISSUE TITLE
👍 U+1F44D Thumbs Up oriented wrong

### ISSUE THREAD

**Issue by Crissov** [EmojiTwo/emojitwo#78]
https://github.com/Ranks/emojione-assets/issues/7
https://github.com/Ranks/emojione/issues/344

![👍 U+1F44D Thumbs Up Sign](https://rawgit.com/EmojiTwo/emojitwo/master/png/1f44d.png) ![🖒 U+1F592 Reversed Thumbs Up Sign](https://rawgit.com/EmojiTwo/emojitwo/master/png/1f592.png) 
![👎 U+1F44E Thumbs Up Sign](https://rawgit.com/EmojiTwo/emojitwo/master/png/1f44e.png) ![🖓 U+1F593 Reversed Thumbs Down Sign](https://rawgit.com/EmojiTwo/emojitwo/master/png/1f593.png)

Most single-hand emojis and non-emoji symbols in the reference glyphs of Unicode look like the reader would see their right hand (exception: down and left pointing index fingers). Emojione uses the other hand for 👍 U+1F44D Thumbs Up. That would be the appropriate emoji glyph for U+1F592 🖒, which is not (yet) marked as an emoji character in Unicode, but see https://github.com/Ranks/emojione/issues/342. 

- Preferred solution: flip the image and add graphics to the _reversed_ code points.
- Alternative solution: make it show the back of the hand.

**Comment by KAMiKAZOW** [comment]
AFAIK "reversed hand" means that the back of the hand is shown, not if it is the left or the right hand.

**Comment by Crissov** [comment]
I totally forgot I had already flipped U+1F44D when Emojitwo still lived only in my user account.
